package Array;

// Find the difference
// Given two strings s and t which consist of only lowercase letters.
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Find the letter that was added in t.

public class FindTheDifference {

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd","abcde"));
    }

    public static char findTheDifference(String s, String t) {
        int sVal = 0;
        int tVal = 0;
        for(int i=0;i<s.length();i++)
            sVal += s.charAt(i);
        for (int i=0;i<t.length();i++)
            tVal += t.charAt(i);
        return (char) (tVal-sVal);
    }
}
